version: '3'
services:
  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - ./magento:/magento
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend
  db:
    image: mysql:latest
    restart: always
    env_file:
      - .env
    networks:
      - backend
  php:
    build: ./php
    restart: always
    volumes:
      - ./magento:/magento
    networks:
      - backend
networks:
  backend:
    driver: "bridge"

